
name: test_existence
on:  
  workflow_dispatch:
  pull_request:    
    branches:
    - main  
  push:
    branches:
    - main


jobs:
    run_scripts:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install testing dependencies
        run: |
          sudo apt-get install libhdf5-serial-dev
          git clone --single-branch --branch develop --depth 1 https://github.com/openmc-dev/openmc.git
          cd openmc
          mkdir build
          cd build
          cmake ..
          make -j2
          sudo make -j2 install
          cd ..
          pip install .
          cd ..
          pip install .

        # this just check the scripts are accessible after the install
        # the scripts are not run or checked for correct behaviour
      - name: Test convert scripts exist
        run: |
          convert_fendl --help
          convert_jeff32 --help
          convert_jeff33 --help
          convert_lib80x --help
          convert_mcnp70 --help
          convert_mcnp71 --help
          convert_nndc71 --help
          convert_tendl --help

      - name: Test generate scripts exist
        run: |
          generate_cendl --help
          generate_endf --help
          generate_jeff33 --help
          generate_jendl --help
      
      - name: Test download h5 scripts exist
        run: |
          download_nndc --help

      - name: Test download chain files scripts exist
        run: |
          download_nndc_chain --help
   
      - name: Test other scripts exist
        run: |
          combine_libraries --help
          convert_tendl_rand --help
          # make_compton --help commented out as the script needs adapting
          # make_stopping_powers --help commented out as the script needs adapting
          sample_sandy --help

      - name: Test depletion scripts exist
        run: |
          add_branching_ratios --help
          generate_endf71_chain_casl --help
          generate_endf_chain --help
          generate_serpent_fissq --help
          generate_tendl_chain --help
          reduce_chain --help
